version: '3'
services:
    laravel.test:
        container_name: api_laravel
        build:
            context: ./api/vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - './api:/var/www/html'
        networks:
            - sail

    front:
        container_name: front_react
        build:
            context: .
            dockerfile: ./front/Dockerfile
        ports:
            - 3000:3000
        networks:
            - sail
networks:
    sail:
        driver: bridge
